import { auth } from "firebase"
import Head from "next/head"
import Image from "next/image"
import { useAuth } from "../lib/auth"
import styles from "../styles/Home.module.css"

import { UpDownIcon } from "styles/iconsSVG"

import {
  Button,
  Code,
  Heading,
  VStack,
  HStack,
  Icon,
  Text,
  Box,
  Flex,
} from "@chakra-ui/react"

import DashboardShell from "components/DashboardShell"
import FreePlanEmptyState from "components/FreePlanEmptyState"
import EmptyState from "components/EmptyState"

export default function Home() {
  const auth = useAuth()
  console.log(auth)
  return (
    <>
      <Head>
        <title>Swift Feedback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        as="main"
        direction="column"
        align="center"
        justify="center"
        w="full"
        h="100vh"
      >
        <HStack>
          <Heading className={styles.title}>
            Swift <a href="https://nextjs.org">Feedback</a>
          </Heading>
          {/* <Icon viewBox="0 0 46 32" boxSize={8}>
            {" "}
            <path
              d="M19.557.113C11.34.32 9.117 8.757 9.03 12.95c1.643-2.67 4.62-3.08 6.931-3.08 2.825.085 10.27.205 17.458 0C40.61 9.663 44.802 3.28 46 .112c-5.391-.085-18.228-.205-26.443 0zM14.422 14.234C3.332 14.234-.468 24.76.045 31.948c3.594-6.418 7.617-7.53 9.243-7.445h6.675c5.956 0 11.039-6.846 12.836-10.27H14.422z"
              fill="currentColor"
            />
          </Icon> */}
          <UpDownIcon boxSize={8} /> {/*using create icon chakra ui */}
        </HStack>

        {auth.user ? (
          <>
            <Button onClick={(e) => auth.signout()}>Sign Out</Button>
          </>
        ) : (
          <Button
            mt={4}
            variant="link"
            size="sm"
            onClick={(e) => auth.signinWithGithub()}
          >
            Sign In
          </Button>
        )}
      </Flex>
    </>
  )
}
